### ISSUE TITLE
SRT file support?

### ISSUE THREAD

**Issue by swindlesmccoop** [SonicMastr/Vita-Media-Player#1]
I get not being able to play MKVs, that's a daunting task for how low-power the Vita is. If I want to watch anime on my Vita, though, I'm not trying to re-encode literally all of my episodes to MP4 just to bake in some subs. It would be much more convenient to have the program run a check to see if there is an SRT with the same name as the selected MP4 and load both files together. This way I won't have to re-encode all of my library that's already MP4 with no subs baked in.

Sorry if that's confusing - it's 7 A.M.

**Comment by Invictaz** [comment]
Second this, most subtitle files are already SRT
Maybe this could be of some use, it has SRT and VTT support.
https://github.com/vitasdk/vita-headers/pull/576

**Comment by SonicMastr** [comment]
SRT support is a good idea and should be trivial to implement. I'll work on this one as soon as I'm done with today.
